Neos:
  RedirectHandler:
    statusCode:
      redirect: 301
      gone: 410

  Neos:
    userInterface:
      translation:
        autoInclude:
          'Neos.RedirectHandler.Ui': ['Modules']
    modules:
      management:
        submodules:
          redirectHandlerUiModule:
            label: 'Neos.RedirectHandler.Ui:Modules:module.label'
            controller: '\Neos\RedirectHandler\Ui\Controller\ModuleController'
            description: 'Neos.RedirectHandler.Ui:Modules:module.description'
            icon: 'icon-mail-forward'
            resource: 'Neos.RedirectHandler.Ui:Backend.Module'
            privilegeTarget: 'Neos.RedirectHandler.Ui:Module'
